name: Continuous Deployment of App
on: 
  push:
    branches:
      - main
jobs:
  Re-deploy-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code in the Ubuntu Runner
        uses: actions/checkout@v6

      - name: Start the ssh-agent in the runner
        uses: webfactory/ssh-agent@v0.9.1
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add the remote server to the runner's known_hosts
        run: |
          mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into the server from the runner
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /home/${{secrets.SERVER_USER}}/test-github-actions &&
            git pull origin main &&
            ~/.bun/bin/bun i &&
            docker compose up -d --build
          "
